const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const WhiteLabelPartner = sequelize.define('WhiteLabelPartner', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  // Partner company info
  userId: {
    type: DataTypes.UUID,
    allowNull: false,
    references: {
      model: 'users',
      key: 'id'
    },
    comment: 'Admin user managing this partnership'
  },
  companyName: {
    type: DataTypes.STRING,
    allowNull: false,
    unique: true
  },
  contactEmail: {
    type: DataTypes.STRING,
    allowNull: false
  },
  contactPhone: {
    type: DataTypes.STRING,
    allowNull: true
  },
  
  // Branding
  brandName: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: 'Their platform name'
  },
  logoUrl: {
    type: DataTypes.STRING,
    allowNull: true
  },
  primaryColor: {
    type: DataTypes.STRING,
    defaultValue: '#00ff88',
    comment: 'Brand color hex code'
  },
  customDomain: {
    type: DataTypes.STRING,
    allowNull: true,
    unique: true,
    comment: 'Their custom domain (e.g., trade.partnerbrand.com)'
  },
  
  // Tier & Pricing
  tier: {
    type: DataTypes.ENUM('basic', 'professional', 'enterprise'),
    defaultValue: 'basic'
  },
  monthlyFee: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: false,
    comment: 'Base monthly licensing fee'
  },
  
  // Revenue Sharing
  revenueSharePercent: {
    type: DataTypes.DECIMAL(5, 2),
    defaultValue: 70,
    comment: 'Partner gets 70%, platform keeps 30% (Stream #8)'
  },
  totalRevenueGenerated: {
    type: DataTypes.DECIMAL(20, 8),
    defaultValue: 0,
    comment: 'Total revenue generated by this partner'
  },
  platformShareCollected: {
    type: DataTypes.DECIMAL(20, 8),
    defaultValue: 0,
    comment: 'Platform\'s 30% share (Stream #8)'
  },
  partnerSharePaid: {
    type: DataTypes.DECIMAL(20, 8),
    defaultValue: 0,
    comment: 'Partner\'s 70% share paid out'
  },
  
  // Features enabled
  features: {
    type: DataTypes.JSON,
    defaultValue: {
      trading: true,
      staking: false,
      lending: false,
      nftMarketplace: false,
      copyTrading: false,
      ownToken: false
    }
  },
  
  // API Access
  apiKeyId: {
    type: DataTypes.UUID,
    allowNull: true,
    references: {
      model: 'api_keys',
      key: 'id'
    }
  },
  webhookUrl: {
    type: DataTypes.STRING,
    allowNull: true,
    comment: 'Partner webhook for events'
  },
  
  // Stats
  totalUsers: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    comment: 'Users on their platform'
  },
  totalTrades: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  },
  totalVolume: {
    type: DataTypes.DECIMAL(20, 8),
    defaultValue: 0,
    comment: 'Total trading volume in USD'
  },
  
  // Status
  status: {
    type: DataTypes.ENUM('pending', 'active', 'suspended', 'terminated'),
    defaultValue: 'pending'
  },
  activatedAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  lastPayoutAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  nextPayoutDate: {
    type: DataTypes.DATE,
    allowNull: true
  },
  
  // Contract
  contractSignedAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  contractDocumentUrl: {
    type: DataTypes.STRING,
    allowNull: true
  },
  notes: {
    type: DataTypes.TEXT,
    allowNull: true
  }
}, {
  tableName: 'white_label_partners',
  timestamps: true,
  underscored: true,
  hooks: {
    beforeCreate: (partner) => {
      // Set monthly fee based on tier
      const tierPricing = {
        basic: 4999,      // $4,999/month - trading only
        professional: 9999, // $9,999/month - full features
        enterprise: 19999   // $19,999/month - custom everything
      };
      
      if (!partner.monthlyFee) {
        partner.monthlyFee = tierPricing[partner.tier] || tierPricing.basic;
      }
      
      // Set next payout to first of next month
      const nextPayout = new Date();
      nextPayout.setMonth(nextPayout.getMonth() + 1);
      nextPayout.setDate(1);
      partner.nextPayoutDate = nextPayout;
    }
  }
});

module.exports = WhiteLabelPartner;
